### ISSUE TITLE
Data Type Exception

### ISSUE THREAD

**Issue by agilly1989** [Zuellni/ComfyUI-PickScore-Nodes#3] opened 2024-01-04 06:33 UTC
Using the supplied flow and 2 images I chose (Image Processor Node)

```
Cannot handle this data type: (1, 1, 439, 3), |u1

File "D:\From Git\ComfyUI\execution.py", line 154, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "D:\From Git\ComfyUI\execution.py", line 84, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "D:\From Git\ComfyUI\execution.py", line 77, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "D:\From Git\ComfyUI\custom_nodes\ComfyUI-PickScore-Nodes\pickscore.py", line 46, in process
processor(
File "D:\From Git\ComfyUI\venv\lib\site-packages\transformers\models\clip\processing_clip.py", line 102, in __call__
image_features = self.image_processor(images, return_tensors=return_tensors, **kwargs)
File "D:\From Git\ComfyUI\venv\lib\site-packages\transformers\image_processing_utils.py", line 446, in __call__
return self.preprocess(images, **kwargs)
File "D:\From Git\ComfyUI\venv\lib\site-packages\transformers\models\clip\image_processing_clip.py", line 318, in preprocess
images = [self.resize(image=image, size=size, resample=resample) for image in images]
File "D:\From Git\ComfyUI\venv\lib\site-packages\transformers\models\clip\image_processing_clip.py", line 318, in
images = [self.resize(image=image, size=size, resample=resample) for image in images]
File "D:\From Git\ComfyUI\venv\lib\site-packages\transformers\models\clip\image_processing_clip.py", line 144, in resize
return resize(image, size=output_size, resample=resample, data_format=data_format, **kwargs)
File "D:\From Git\ComfyUI\venv\lib\site-packages\transformers\image_transforms.py", line 275, in resize
image = to_pil_image(image)
File "D:\From Git\ComfyUI\venv\lib\site-packages\transformers\image_transforms.py", line 163, in to_pil_image
return PIL.Image.fromarray(image)
File "D:\From Git\ComfyUI\venv\lib\site-packages\PIL\Image.py", line 3092, in fromarray
raise TypeError(msg) from e
```

**Comment by Zuellni** [comment] 2024-01-05 17:45
Are you using the portable version of ComfyUI? Do you have any other custom nodes enabled? What dimensions are your input images?

**Comment by agilly1989** [comment] 2024-01-05 20:24
- Are you using the portable version of ComfyUI?
    - No, I downloaded it and I am using it in a 3.11.x virtual environment
        - See https://github.com/comfyanonymous/ComfyUI?tab=readme-ov-file#manual-install-windows-linux
- Do you have any other custom nodes enabled?
    - Yes, See below as I will attach my `comfyui.log`
- What dimensions are your input images?
    - Doesn't matter. I tried
        - Source size images (different sizes)
        - Scaling image A to 512px on the longest side and resizing image B to be the same size
        - Scaling image A to 512px on the shortest side and resizing image B to be the same size
        - Resizing image A to 512x512 resizing image B to be the same size
        - Resizing image A to 1024x1024 resizing image B to be the same size

[comfyui.log](https://github.com/Zuellni/ComfyUI-PickScore-Nodes/files/13846264/comfyui.log)

**Comment by shiloh92** [comment] 2024-01-28 04:03
Same situation, not working with most up to date version of ComfyUI , transformers possibly related error?

Error: Cannot handle data type (1, 1, 768, 3), |u1

    ZuellniPickScoreImageProcessor: Unsupported data type
    File "execution.py", line 155: recursive_execute function
    File "execution.py", line 85: get_output_data function
    File "execution.py", line 78: map_node_over_list function
    File "pickscore.py", line 46: process function in pickscore module
    File "processing_clip.py", line 102: call method in processing_clip module
    File "image_processing_utils.py", line 446: call method in image_processing_utils module
    File "image_processing_clip.py", line 318: preprocess method in image_processing_clip module
    File "image_processing_clip.py", line 318: resize method in image_processing_clip module
    File "resize" method in image_transforms module: TypeError, invalid array conversion

**Comment by Zuellni** [comment] 2024-01-28 11:03
Sorry, I can't quite figure this one out, the issue being that it Just Works For Me™ no matter what I throw at it. It could be some other node interfering like in #2, but I couldn't find anything special about the ones in the log above. Still, you can try running it without any other nodes enabled. Also, are you both able to run the inference code from the [PickScore](https://github.com/yuvalkirstain/PickScore?tab=readme-ov-file#inference-with-pickscore) repo without any errors?

**Comment by Zuellni** [comment] 2024-06-11 10:04
Closing for now since I still can't reproduce.

**Closed as not planned by Zuellni** 2024-06-11 10:04 UTC
